<h1>Une erreur est survenue</h1> 
<h2><?php echo $this->message; ?></h2>

<?php if ('development' == APPLICATION_ENV): ?>

    <h3>Information:</h3>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage(); ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString(); ?></pre>

    <h3>Paramètres:</h3>
    <pre><?php var_dump($this->request->getParams()) ?></pre>

<?php endif ?>
